Sylius/InvoicingPlugin

src/Entity/InvoiceSequence.php

It results in bug in application using this plugin :(
```
Unable to create a proxy for a final class "Sylius\InvoicingPlugin\Entity\InvoiceSequence"
```

Remove final from InvoiceSequence

---

.travis.yml
spec/EventProducer/OrderPlacedProducerSpec.php
src/DependencyInjection/SyliusInvoicingExtension.php
src/EventProducer/OrderPlacedProducer.php
src/Resources/config/services.xml
tests/Application/.gitignore

Introduced in https://github.com/Sylius/InvoicingPlugin/pull/33
The problem was when fixtures were used, Order was not yet persisted, then it could not be fetched from the repository. The best solution right now is reacting on doctrine events (:/) instead of state machine callback. Maybe we'll figure out better solution in the future.

React with OrderPlaced event on doctrine event instead of SM callback

---

src/Resources/views/Invoice/Download/pdf.html.twig

Some currency symbols are rendered weirdly if you don't specify the charset in the rendered HTML page. (eg. the € symbol)

Fixed currency symbols rendering with UTF-8 encoding

---

migrations/Version20180801083047.php

Only migrations in the `Sylius\Migrations` namespace will be executed.

Fixed migration namespace

---

src/Resources/config/config.yml

KnpSnappyBundle already provides a more sensible default: https://github.com/KnpLabs/KnpSnappyBundle/blob/v1.5.2/DependencyInjection/Configuration.php#L41

Remove hardcoded binary path for wkhtmltopdf

---

migrations/Version20180626120743.php
migrations/Version20180711070226.php
migrations/Version20180711084815.php
migrations/Version20180801083047.php
migrations/Version20180826064735.php

Namespace migrations in Sylius-Standard is now `DoctrineMigrations` (see https://github.com/Sylius/Sylius-Standard/blob/master/config/packages/doctrine_migrations.yaml#L5), therefore we should follow this convention

Change migrations namespace

---

src/Resources/translations/messages.fr.yml

Fix #44
There is an issue with the colon in Sylius. In French we need to have a **non-breaking space** before it. That's why it should be in the message itself and not in the code.
An example:
https://github.com/Sylius/InvoicingPlugin/blob/e91c56d357736df712ee0980261a914c04fc38a4/src/Resources/views/Invoice/Download/pdf.html.twig#L10
WDYT?

Add messages for fr locale

---

src/Command/SendInvoiceEmail.php
src/EventListener/OrderPaymentPaidListener.php
src/Ui/Action/DownloadInvoiceAction.php
src/Ui/Menu/AdminMenuListener.php

It was the same as the Credit memo, now it's using the 'file' icon.

Changed the invoice icon

---

features/managing_channels/editing_shop_billing_data_on_channel.feature
tests/Behat/Resources/suites/admin/managing_channels.yml

It occurred that there already is a `@managing_channels` tag in Sylius/Sylius as well as `ui_managing_channels` suite. Therefore, channel-related tests from InvoicingPlugin were loaded by suite used by Sylius/Sylius and fail due to undefined steps. 
The problem occurred only while running InvocingPlugin tests with Sylius/Sylius installed as a dependency.

Resolving suites/tags conflict

---

src/Resources/config/app/routing/admin_invoicing.yml
src/Resources/config/config.yml
src/Resources/config/services.xml

Fixes https://github.com/Sylius/InvoicingPlugin/issues/84
Ok, I think we've finally managed (kinda) to resolve this problem 😄 There are some problems in Sylius (or even in Symfony itself) with overwriting templates, that are not configured with a one, specific path style. It should always follow `@SyliusTestPlugin/Catalog/templateName.html.twig` convention - and as you can see, there were some other conventions used :) It would be good if someone could test these changes before merging (cc @itwhy), but I've tested all plugin templates on a fresh Sylius-Standard application and it worked 🚀

Make all plugin templates possible to overwrite

---

composer.json
src/Entity/BillingData.php
src/Entity/Invoice.php
src/Entity/InvoiceChannel.php
src/Entity/InvoiceShopBillingData.php
src/Entity/LineItem.php
src/Entity/TaxItem.php
src/Resources/config/doctrine/BillingData.orm.xml
src/Resources/config/doctrine/Invoice.orm.xml
src/Resources/config/doctrine/LineItem.orm.xml
src/Resources/config/doctrine/TaxItem.orm.xml

This makes it possible to extend entities in sylius-like manner.
Closes #128, fixes #120.

Make entities extendable

---

src/Cli/GenerateInvoicesCommand.php

Supposedly those are cart orders and should not be selected for invoice generation

Fix GenerateInvoicesCommand selects order without number

---

composer.json
src/Cli/GenerateInvoicesCommand.php

Like https://github.com/Sylius/ShopApiPlugin/pull/602: allow upgrade to symfony 4.4

fix(deps): loosen constraint for symfony/messenger

---

src/DependencyInjection/SyliusInvoicingExtension.php
tests/Application/config/packages/doctrine_migrations.yaml

Fixes #192 
Without this change, migrations are generated into the plugin's directory rather than `src/Migrations`. I'm wondering do we need/want to have a test for the proper migrations directory like in [the PayPalPlugin](https://github.com/Sylius/PayPalPlugin/pull/163/commits/b1d268568ec523fe9b707830d11c6d2b58917c93)? 🤷‍♂️

Fix Doctrine/Migrations configuration

---

src/Resources/views/Invoice/Download/pdf.html.twig

`sylius_invoicing_plugin.ui.invoice` and `sylius_invoicing_plugin.ui.issued_at` are in `translations/messages`.

Add translation in invoice PDF file

---

UPGRADE.md
spec/CommandHandler/SendInvoiceEmailHandlerSpec.php
spec/Creator/InvoiceCreatorSpec.php
spec/Entity/InvoiceSpec.php
spec/EventProducer/OrderPaymentPaidProducerSpec.php
spec/Factory/InvoiceFactorySpec.php
spec/Generator/InvoiceGeneratorSpec.php
src/CommandHandler/SendInvoiceEmailHandler.php
src/Creator/InvoiceCreator.php
src/Doctrine/ORM/InvoiceRepository.php
src/Doctrine/ORM/InvoiceRepositoryInterface.php
src/Entity/Invoice.php
src/Entity/InvoiceInterface.php
src/EventProducer/OrderPaymentPaidProducer.php
src/Factory/InvoiceFactory.php
src/Factory/InvoiceFactoryInterface.php
src/Generator/InvoiceGenerator.php
src/Migrations/Version20210607115930.php
src/Resources/config/doctrine/Invoice.orm.xml
src/Resources/views/Invoice/Email/invoiceGenerated.html.twig
src/Resources/views/Invoice/Show/_header.html.twig
tests/Behat/Context/Domain/GeneratingInvoiceContext.php
tests/Behat/Context/Ui/Admin/ManagingInvoicesContext.php
tests/Behat/Context/Ui/Shop/CustomerBrowsingInvoicesContext.php

Similar to https://github.com/Sylius/RefundPlugin/pull/306 and https://github.com/Sylius/RefundPlugin/pull/307.
Should be easier to operate on the Invoice with a proper relation rather than just an order number

Relate Invoice with Order

---

spec/Command/SendInvoiceEmailSpec.php
spec/CommandHandler/SendInvoiceEmailHandlerSpec.php
spec/Converter/BillingDataConverterSpec.php
spec/Converter/InvoiceShopBillingDataConverterSpec.php
spec/Converter/LineItemsConverterSpec.php
spec/Converter/TaxItemsConverterSpec.php
spec/Creator/InvoiceCreatorSpec.php
spec/Creator/MassInvoicesCreatorSpec.php
spec/Entity/BillingDataSpec.php
spec/Entity/InvoiceSpec.php
spec/Entity/LineItemSpec.php
spec/Entity/TaxItemSpec.php
spec/Event/OrderPaymentPaidSpec.php
spec/Event/OrderPlacedSpec.php
spec/EventListener/CreateInvoiceOnOrderPlacedListenerSpec.php
spec/EventListener/OrderPaymentPaidListenerSpec.php
spec/EventProducer/OrderPaymentPaidProducerSpec.php
spec/EventProducer/OrderPlacedProducerSpec.php
spec/Factory/InvoiceFactorySpec.php
spec/Generator/InvoiceGeneratorSpec.php
spec/Generator/InvoicePdfFileGeneratorSpec.php
spec/Generator/SequentialInvoiceNumberGeneratorSpec.php
spec/Generator/UuidInvoiceIdentifierGeneratorSpec.php
spec/Model/InvoicePdfSpec.php
spec/Provider/ChannelColorProviderSpec.php
spec/Security/Voter/InvoiceVoterSpec.php

According to the convention proposed by [PHPSpec itself](http://www.phpspec.net/en/stable/manual/getting-started.html#specifying-behaviour), as well as [convention on Sylius/Sylius repository](https://github.com/Sylius/Sylius/blob/master/ecs.php#L26).

Do not require visibility in PHPSpec functions

---

README.md

The configuration for the WKHTMLTOPDF_PATH is in the .env file, the yaml configuration file uses the environment variable.

change information on WKHTMLTOPDF_PATH in README

---

UPGRADE.md
features/managing_invoices/seeing_payment_state_on_invoice.feature
spec/Entity/InvoiceSpec.php
spec/Factory/InvoiceFactorySpec.php
spec/Generator/InvoiceGeneratorSpec.php
src/Entity/Invoice.php
src/Entity/InvoiceInterface.php
src/Factory/InvoiceFactory.php
src/Factory/InvoiceFactoryInterface.php
src/Generator/InvoiceGenerator.php
src/Migrations/Version20210811092457.php
src/Migrations/Version20210812125029.php
src/Resources/config/doctrine/Invoice.orm.xml
src/Resources/translations/messages.en.yml
src/Resources/views/Invoice/Download/pdf.html.twig
src/Resources/views/Invoice/show.html.twig
tests/Behat/Context/Ui/Admin/ManagingInvoicesContext.php
tests/Behat/Page/Admin/Invoice/ShowPage.php
tests/Behat/Page/Admin/Invoice/ShowPageInterface.php

[Invoice] Add payment status

---

phpstan.neon
src/Entity/InvoiceShopBillingData.php
src/Entity/InvoiceShopBillingDataInterface.php
src/Entity/LineItem.php
src/Entity/LineItemInterface.php
src/Entity/TaxItem.php
src/Entity/TaxItemInterface.php

These ids were integers for years already
https://github.com/Sylius/InvoicingPlugin/blob/93a4fa83b89b0a10ce6fde34807e0a9074524892/src/Resources/config/doctrine/InvoiceShopBillingData.orm.xml#L10-L12
https://github.com/Sylius/InvoicingPlugin/blob/93a4fa83b89b0a10ce6fde34807e0a9074524892/src/Resources/config/doctrine/LineItem.orm.xml#L5-L7
https://github.com/Sylius/InvoicingPlugin/blob/93a4fa83b89b0a10ce6fde34807e0a9074524892/src/Resources/config/doctrine/TaxItem.orm.xml#L5-L7

[Maintenance] Remove wrong return types

---

spec/Generator/InvoiceGeneratorSpec.php
src/Generator/InvoiceGenerator.php

Change conditions settings Invoice Payment state.
`$order->getPaymentState()` is returning a string from `OrderPaymentStates`, therefore Invoice status is never set to `'completed'`

Fix invoice payment state not updating when given order is paid

---

README.md
UPGRADE.md
src/Resources/config/config.yml
src/Resources/config/services.xml
src/Resources/config/services/ui.xml
src/Resources/views/Invoice/Grid/Field/channel.html.twig
src/Resources/views/Invoice/Show/_header.html.twig
src/Resources/views/Invoice/show.html.twig
src/Resources/views/Order/Admin/_invoices.html.twig
tests/Behat/Page/Admin/Invoice/ShowPage.php

1.  Replace channel color feature with sylius/sylius standard template
* Header of invoice show page
Before
After
* Channel column for invoices index page
Before
After
* Order show page, list of invoices
Before
After
2. Move breadcrumb block at invoices admin show page to correct place as for other CRUD templates
Before
After
3. Move seller/buyer blocks on top of the page, same as for CreditMemo show page
Before
After
4. Wrap action buttons with button group for order's invoices list (Download btn colored blue as secondary action blue in the same schema as for credit memo download btn. "Resend" btn left grey the same as for "resend order confirmation"/"resend shipment confirmation" btns)
Before
After
And credit memos for context (Do ignore slightly non-standard view, artifact of the …

Minor admin ui redesign

---

spec/Entity/LineItemSpec.php
src/Entity/LineItem.php

When the name, price and tax are the same whereas the variant is not the same, it's merged. The fix compare the variant to be sure.

fix: compare when name is the same but not variant

---

phpstan.neon
src/DependencyInjection/SyliusInvoicingExtension.php
src/Resources/config/config.yml
tests/DependencyInjection/SyliusInvoicingExtensionTest.php

Before this change, resources and their parameters were loaded too late and they cannot be used properly for example in a grid or state machine configuration.

[DependencyInjection] Move registering resources to prepend method

---

src/Cli/GenerateInvoicesCommand.php
src/Resources/config/services/cli.xml

Non-BC maintenance change.
1. While command was already lazy loaded via DI definition, I think it's a better practice to keep command name in class itself + removal of misuse of constructor call.
https://symfony.com/doc/current/console/commands_as_services.html#lazy-loading
2. It's good practice to define `parent::__construct()` last. No practical difference for the current setup though.
https://symfony.com/doc/4.4/console.html#configuring-the-command
On separate note, will you accept progress bar for this command? It will require to do something with Generators like that
```php
// src/Cli/GenerateInvoicesCommand.php
$this->massInvoicesCreator->setGenerateResult(true);
foreach ($this->massInvoicesCreator->__invoke($orders) as $result) {
$progressBar->advance();
}
// …
```

Update console command definition to SF 4.4 standards

---

src/Migrations/Version20191216134233.php

Fix `down` method of one of the migrations, as there was removed the inexistent foreign key.
Fixes #288

Fix down method of migration that changes indexes

---

.github/workflows/build.yml
composer.json

As Sylius 1.10 is no longer maintained, I think it's high time to remove the support for it.

Drop support for Sylius 1.10

---

src/Resources/views/Invoice/show.html.twig

| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | main             |
| Bug fix?        | yes                                                       |
| New feature?    | no                                                    |
| BC breaks?      | no                                                       |
| Deprecations?   | no |
| Related tickets |                 |
| License         | MIT                                                          |
Fix in Admin Show Invoice : use admin locale instead of invoice

[Admin][Translation] fix : use admin locale instead of invoice

---

src/Resources/config/services.xml
src/Resources/config/services/listeners/workflow.xml

The event listener for `symfony/workflow` can be loaded even if `winzou/state-machine` is still the default state machine.
Before this PR :

[symfony/workflow] Makes workflow event listener loading
