Sylius/InvoicingPlugin

- migrations/Version20180626120743.php
Copying this migration should be mentioned in installation process #7 
as it has been done in [AdminOrderCreationPlugin](https://github.com/Sylius/AdminOrderCreationPlugin/pull/31/files#diff-04c6e90faac2675aa89e2176d2eec7d8R51)
> Add missing migration

- README.md
- src/Resources/config/app/routing.yml
* Installation guide
* Extension points
* routing.yml changes
> Docs update

- .travis.yml
- features/browsing_invoices.feature
- features/downloading_invoices_on_order_view.feature
- features/seeing_invoices_on_order_view.feature
- src/DependencyInjection/SyliusInvoicingExtension.php
- src/Resources/views/Order/_invoices.html.twig
- tests/Behat/Context/Ui/Admin/ManagingInvoicesContext.php
- tests/Behat/Page/Admin/Invoice/IndexPage.php
- tests/Behat/Page/Admin/Invoice/IndexPageInterface.php
- tests/Behat/Page/Admin/Invoice/ShowPage.php
- tests/Behat/Page/Admin/Invoice/ShowPageInterface.php
- tests/Behat/Page/Admin/Order/ShowPage.php
- tests/Behat/Page/Admin/Order/ShowPageInterface.php
- tests/Behat/Page/Admin/OrderShowPage.php
- tests/Behat/Page/Admin/OrderShowPageInterface.php
- tests/Behat/Resources/services.xml
> [Admin][Order] Add button for downloading an invoice on order show page

- tests/Behat/Context/Ui/Admin/ManagingInvoicesContext.php
- tests/Behat/Page/Admin/Order/ShowPage.php
- tests/Behat/Page/Admin/Order/ShowPageInterface.php
Fixes for: https://github.com/Sylius/InvoicingPlugin/pull/6
> [Maintenance] Fixes after PR review

- features/downloading_invoices_on_customer_order_view.feature
- features/seeing_invoice.feature
- src/Resources/views/Invoice/show.html.twig
- tests/Behat/Context/Ui/Admin/ManagingInvoicesContext.php
- tests/Behat/Context/Ui/Shop/CustomerBrowsingInvoicesContext.php
- tests/Behat/Page/Admin/Invoice/ShowPage.php
- tests/Behat/Page/Admin/Invoice/ShowPageInterface.php
```
Scenario: Downloading invoice
Given I view the summary of the invoice for order "#00000666"
When I click on download button
Then the pdf file for this invoice should be downloaded successfully
```
> I want to download invoice as pdf file on invoice view

- spec/Email/InvoiceEmailSenderSpec.php
- spec/Entity/LineItemSpec.php
- spec/Event/OrderPlacedSpec.php
- spec/EventListener/CreateInvoiceOnOrderPlacedListenerSpec.php
- spec/EventListener/OrderPaymentPaidListenerSpec.php
- spec/EventProducer/OrderPaymentPaidProducerSpec.php
- spec/EventProducer/OrderPlacedProducerSpec.php
- spec/Generator/SequentialInvoiceNumberGeneratorSpec.php
- src/DependencyInjection/SyliusInvoicingExtension.php
- src/Email/InvoiceEmailSender.php
- src/Event/OrderPlaced.php
- src/EventListener/CreateInvoiceOnOrderPlacedListener.php
- src/EventListener/OrderPaymentPaidListener.php
- src/EventProducer/OrderPlacedProducer.php
- src/File/TemporaryFileSystemInterface.php
- src/Generator/InvoiceGenerator.php
- src/Generator/SequentialInvoiceNumberGenerator.php
- src/Resources/config/services.xml
Fixes https://github.com/Sylius/InvoicingPlugin/issues/10
> Send order number in OrderPlaced event

- migrations/Version20180801083047.php
- spec/Entity/InvoiceSpec.php
- spec/Generator/InvoiceGeneratorSpec.php
- src/Entity/Invoice.php
- src/Entity/InvoiceInterface.php
- src/Generator/InvoiceGenerator.php
- src/Resources/config/doctrine/Invoice.orm.xml
- src/Resources/views/Invoice/Download/pdf.html.twig
- tests/Application/app/config/config_test.yml
Fixes https://github.com/Sylius/InvoicingPlugin/issues/13
> Locale code added to invoice model

- src/Resources/config/config.yml
fixes https://github.com/Sylius/InvoicingPlugin/issues/51
> Invoice id filter removed

- features/managing_invoices/downloading_invoices_on_admin_order_view.feature
- features/managing_invoices/seeing_invoice.feature
- features/managing_invoices/seeing_invoices_on_order_view.feature
- src/Resources/views/Invoice/show.html.twig
- tests/Behat/Context/Ui/Admin/ManagingInvoicesContext.php
- tests/Behat/Page/Admin/Invoice/ShowPage.php
- tests/Behat/Page/Admin/Invoice/ShowPageInterface.php
fixes https://github.com/Sylius/InvoicingPlugin/issues/42
> Resend button usable on invoice view + behat tests fixes

- README.md
- docs/legacy_installation.md
**17 additions & 59 deletions** in `README` file, Symfony Flex totally rocks 😄 🤘
> Describe installation with Symfony Flex

- src/Entity/ShopBillingDataAwareInterface.php
- src/Entity/ShopBillingDataTrait.php
> Delete unnecessary Channel::tax_id field

- features/managing_invoices/resending_invoices_to_customer.feature
- src/Resources/config/services.xml
- src/Resources/translations/flashes.en.yml
- src/Ui/Action/Admin/ResendInvoiceAction.php
- tests/Behat/Context/Ui/Admin/ManagingInvoicesContext.php
- tests/Behat/Page/Admin/Invoice/ShowPage.php
- tests/Behat/Page/Admin/Invoice/ShowPageInterface.php
- tests/Behat/Page/Admin/Order/ShowPage.php
- tests/Behat/Page/Admin/Order/ShowPageInterface.php
- tests/Behat/Page/Shop/Order/DownloadInvoicePage.php
- tests/Behat/Page/Shop/Order/DownloadInvoicePageInterface.php
- tests/Behat/Page/Shop/Order/ShowPage.php
- tests/Behat/Resources/services.xml
Fixes https://github.com/Sylius/InvoicingPlugin/issues/64
> Flash message displayed after resending an invoice

- src/Resources/translations/messages.en.yml
Based on https://github.com/Sylius/InvoicingPlugin/pull/88
Fixes https://github.com/Sylius/InvoicingPlugin/issues/63
> Rename invoice related columns

- composer.json
Ideally it should go away, but this solution will fix the downstream packages for now.
> Hotfix for TestOrderPlacedProducer

- src/Resources/config/app/routing/admin_invoicing.yml
- src/Resources/config/config.yml
- src/Resources/config/services/ui.xml
- src/Resources/views/Invoice/Grid/Field/orderNumber.html.twig
- src/Ui/RedirectToOrderShowAction.php
**Before:**
**After:**
**Link before clicking:**
**After Clicking:**
> [Admin] Unify order link in InvocingPlugin

- README.md
- UPGRADE.md
> [Docs] Update of UPGRADE file and installation instruction

- composer.json
Extracted commit of @Prometee from #186
> Add conflict to ^8.3.25 of symplify/package-builder to fix the build

- UPGRADE.md
> Update upgrade to v0.12.0

- src/DependencyInjection/Configuration.php
- src/Entity/InvoiceShopBillingData.php
- src/Resources/config/doctrine/Invoice.orm.xml
This PR allows extends the InvoiceShopBillingData entity.
> allow override invoice shop billing data

- README.md
> Bugfix | Update README file to use new route format

- UPGRADE.md
> Add note to UPGRADE filem about removing TemporaryFilesystem

- tests/Application/config/packages/knp_snappy.yaml
After some changes in knp the options: [] does not work. With tihs changes it should be fixed.
> Update knp snappy file

- src/Resources/views/Invoice/Download/pdf.html.twig
- src/Resources/views/Invoice/Download/pdfLayout.html.twig
After https://github.com/Sylius/InvoicingPlugin/pull/251/files#r716506932
> [PDF] Fix minor locale code typo

- src/Resources/config/services.xml
this should solve the problem with unresolved parameters in .env variables  from #254
> resolve SYLIUS_INVOICING_LOGO_FILE

- .github/workflows/build.yml
According to the comment: https://github.com/Sylius/InvoicingPlugin/pull/278#discussion_r858580775
> [GitHub Actions] Include build with PDF generation disabled to the main workflow

- spec/Fixture/Listener/InvoicesPurgerListenerSpec.php
- src/Fixture/Listener/InvoicesPurgerListener.php
- src/Resources/config/config.yml
- src/Resources/config/services/fixtures.xml
without purging catalog with invoices, we get an error of duplicated invoices while fixtures run
> Add directory purger before fixtures run

- tests/Behat/Context/Ui/Admin/ManagingInvoicesContext.php
After https://github.com/Sylius/InvoicingPlugin/pull/287
> [Behat][Invoice] Fix usage of method checking line items after last changes

- .github/workflows/build.yml
- composer.json
- phpstan.neon
- src/Resources/config/app/routing/shop_invoicing.yml
- src/Resources/config/services/actions.xml
- src/Ui/Action/Admin/ResendInvoiceAction.php
- tests/Application/config/packages/security.yaml
- tests/Application/config/packages/test/framework.yaml
- tests/Application/config/packages/test_cached/framework.yaml
- tests/Application/config/routes/sylius_shop.yaml
- tests/Application/src/Kernel.php
To be merged on Sylius 1.12 release :woman_dancing:
In addition, https://github.com/Sylius/InvoicingPlugin/pull/295 and https://github.com/Sylius/InvoicingPlugin/pull/294 should be merged before this one then the rebase will be needed.
> Add Symfony 6 support

- src/Resources/views/Order/Shop/_invoices.html.twig
PR based on https://github.com/Sylius/InvoicingPlugin/pull/296 – rebase needed before the merge.
Before:
After:
> [Templates] Adjust to the new Sylius shop UI styles

- .github/workflows/build.yml
- tests/Application/.env.test
Let's remove the binary from the repo and install it in the GitHub Actions.
> [Maintenance] Remove wkhtmltopdf binary

- src/Security/Voter/InvoiceVoter.php
See issue: https://github.com/Sylius/InvoicingPlugin/issues/298
> Loosen type check for user, to handle more types of users

- src/Resources/views/Invoice/Download/pdf.html.twig
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | main             |
| Bug fix?        | yes                                                       |
| New feature?    | no                                                    |
| BC breaks?      | no                                                       |
| Deprecations?   | no |
| Related tickets |                 |
| License         | MIT                                                          |
Fix translation on pdf template
> [PDF Template][Translation] Fix translation on pdf template
